<h1>Add New Testimonial</h1>
<?php if ($this->canPost()): ?>
<div class="info"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<form action="<?php echo $this->getPostActionUrl() ?>" id="testimonial-form" method="post">
  <label for="post">What you think of us?</label><br />
  <textarea class="input-text required-entry" name="post" id="post" cols="30" rows="10"></textarea>
  <br /><br />
  <button>Send</button>
</form>
<script type="text/javascript">
  //< ![CDATA[
    var testimonialForm = new VarienForm('testimonial-form');
  //]]>
</script>
<?php else: ?>
  <p>Only registered customers can leave testimonial, login <a href="<?php echo Mage::helper('customer')->getLoginUrl() ?>">here</a></p>
<?php endif ?>